name: Release JRebel Plugin

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew release

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: release/*.zip